/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.learninghadoop2.avrotables;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class tweets_avro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"tweets_avro\",\"namespace\":\"com.learninghadoop2.avrotables\",\"fields\":[{\"name\":\"created_at\",\"type\":[\"null\",\"string\"]},{\"name\":\"tweet_id_str\",\"type\":[\"null\",\"string\"]},{\"name\":\"text\",\"type\":[\"null\",\"string\"]},{\"name\":\"in_reply_to\",\"type\":[\"null\",\"string\"]},{\"name\":\"is_retweeted\",\"type\":[\"null\",\"string\"]},{\"name\":\"user_id\",\"type\":[\"null\",\"string\"]},{\"name\":\"place_id\",\"type\":[\"null\",\"string\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence created_at;
  @Deprecated public java.lang.CharSequence tweet_id_str;
  @Deprecated public java.lang.CharSequence text;
  @Deprecated public java.lang.CharSequence in_reply_to;
  @Deprecated public java.lang.CharSequence is_retweeted;
  @Deprecated public java.lang.CharSequence user_id;
  @Deprecated public java.lang.CharSequence place_id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public tweets_avro() {}

  /**
   * All-args constructor.
   */
  public tweets_avro(java.lang.CharSequence created_at, java.lang.CharSequence tweet_id_str, java.lang.CharSequence text, java.lang.CharSequence in_reply_to, java.lang.CharSequence is_retweeted, java.lang.CharSequence user_id, java.lang.CharSequence place_id) {
    this.created_at = created_at;
    this.tweet_id_str = tweet_id_str;
    this.text = text;
    this.in_reply_to = in_reply_to;
    this.is_retweeted = is_retweeted;
    this.user_id = user_id;
    this.place_id = place_id;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return created_at;
    case 1: return tweet_id_str;
    case 2: return text;
    case 3: return in_reply_to;
    case 4: return is_retweeted;
    case 5: return user_id;
    case 6: return place_id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: created_at = (java.lang.CharSequence)value$; break;
    case 1: tweet_id_str = (java.lang.CharSequence)value$; break;
    case 2: text = (java.lang.CharSequence)value$; break;
    case 3: in_reply_to = (java.lang.CharSequence)value$; break;
    case 4: is_retweeted = (java.lang.CharSequence)value$; break;
    case 5: user_id = (java.lang.CharSequence)value$; break;
    case 6: place_id = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'created_at' field.
   */
  public java.lang.CharSequence getCreatedAt() {
    return created_at;
  }

  /**
   * Sets the value of the 'created_at' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.lang.CharSequence value) {
    this.created_at = value;
  }

  /**
   * Gets the value of the 'tweet_id_str' field.
   */
  public java.lang.CharSequence getTweetIdStr() {
    return tweet_id_str;
  }

  /**
   * Sets the value of the 'tweet_id_str' field.
   * @param value the value to set.
   */
  public void setTweetIdStr(java.lang.CharSequence value) {
    this.tweet_id_str = value;
  }

  /**
   * Gets the value of the 'text' field.
   */
  public java.lang.CharSequence getText() {
    return text;
  }

  /**
   * Sets the value of the 'text' field.
   * @param value the value to set.
   */
  public void setText(java.lang.CharSequence value) {
    this.text = value;
  }

  /**
   * Gets the value of the 'in_reply_to' field.
   */
  public java.lang.CharSequence getInReplyTo() {
    return in_reply_to;
  }

  /**
   * Sets the value of the 'in_reply_to' field.
   * @param value the value to set.
   */
  public void setInReplyTo(java.lang.CharSequence value) {
    this.in_reply_to = value;
  }

  /**
   * Gets the value of the 'is_retweeted' field.
   */
  public java.lang.CharSequence getIsRetweeted() {
    return is_retweeted;
  }

  /**
   * Sets the value of the 'is_retweeted' field.
   * @param value the value to set.
   */
  public void setIsRetweeted(java.lang.CharSequence value) {
    this.is_retweeted = value;
  }

  /**
   * Gets the value of the 'user_id' field.
   */
  public java.lang.CharSequence getUserId() {
    return user_id;
  }

  /**
   * Sets the value of the 'user_id' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.CharSequence value) {
    this.user_id = value;
  }

  /**
   * Gets the value of the 'place_id' field.
   */
  public java.lang.CharSequence getPlaceId() {
    return place_id;
  }

  /**
   * Sets the value of the 'place_id' field.
   * @param value the value to set.
   */
  public void setPlaceId(java.lang.CharSequence value) {
    this.place_id = value;
  }

  /** Creates a new tweets_avro RecordBuilder */
  public static com.learninghadoop2.avrotables.tweets_avro.Builder newBuilder() {
    return new com.learninghadoop2.avrotables.tweets_avro.Builder();
  }
  
  /** Creates a new tweets_avro RecordBuilder by copying an existing Builder */
  public static com.learninghadoop2.avrotables.tweets_avro.Builder newBuilder(com.learninghadoop2.avrotables.tweets_avro.Builder other) {
    return new com.learninghadoop2.avrotables.tweets_avro.Builder(other);
  }
  
  /** Creates a new tweets_avro RecordBuilder by copying an existing tweets_avro instance */
  public static com.learninghadoop2.avrotables.tweets_avro.Builder newBuilder(com.learninghadoop2.avrotables.tweets_avro other) {
    return new com.learninghadoop2.avrotables.tweets_avro.Builder(other);
  }
  
  /**
   * RecordBuilder for tweets_avro instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<tweets_avro>
    implements org.apache.avro.data.RecordBuilder<tweets_avro> {

    private java.lang.CharSequence created_at;
    private java.lang.CharSequence tweet_id_str;
    private java.lang.CharSequence text;
    private java.lang.CharSequence in_reply_to;
    private java.lang.CharSequence is_retweeted;
    private java.lang.CharSequence user_id;
    private java.lang.CharSequence place_id;

    /** Creates a new Builder */
    private Builder() {
      super(com.learninghadoop2.avrotables.tweets_avro.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.learninghadoop2.avrotables.tweets_avro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.created_at)) {
        this.created_at = data().deepCopy(fields()[0].schema(), other.created_at);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.tweet_id_str)) {
        this.tweet_id_str = data().deepCopy(fields()[1].schema(), other.tweet_id_str);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.text)) {
        this.text = data().deepCopy(fields()[2].schema(), other.text);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.in_reply_to)) {
        this.in_reply_to = data().deepCopy(fields()[3].schema(), other.in_reply_to);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.is_retweeted)) {
        this.is_retweeted = data().deepCopy(fields()[4].schema(), other.is_retweeted);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.user_id)) {
        this.user_id = data().deepCopy(fields()[5].schema(), other.user_id);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.place_id)) {
        this.place_id = data().deepCopy(fields()[6].schema(), other.place_id);
        fieldSetFlags()[6] = true;
      }
    }
    
    /** Creates a Builder by copying an existing tweets_avro instance */
    private Builder(com.learninghadoop2.avrotables.tweets_avro other) {
            super(com.learninghadoop2.avrotables.tweets_avro.SCHEMA$);
      if (isValidValue(fields()[0], other.created_at)) {
        this.created_at = data().deepCopy(fields()[0].schema(), other.created_at);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.tweet_id_str)) {
        this.tweet_id_str = data().deepCopy(fields()[1].schema(), other.tweet_id_str);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.text)) {
        this.text = data().deepCopy(fields()[2].schema(), other.text);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.in_reply_to)) {
        this.in_reply_to = data().deepCopy(fields()[3].schema(), other.in_reply_to);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.is_retweeted)) {
        this.is_retweeted = data().deepCopy(fields()[4].schema(), other.is_retweeted);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.user_id)) {
        this.user_id = data().deepCopy(fields()[5].schema(), other.user_id);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.place_id)) {
        this.place_id = data().deepCopy(fields()[6].schema(), other.place_id);
        fieldSetFlags()[6] = true;
      }
    }

    /** Gets the value of the 'created_at' field */
    public java.lang.CharSequence getCreatedAt() {
      return created_at;
    }
    
    /** Sets the value of the 'created_at' field */
    public com.learninghadoop2.avrotables.tweets_avro.Builder setCreatedAt(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.created_at = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'created_at' field has been set */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'created_at' field */
    public com.learninghadoop2.avrotables.tweets_avro.Builder clearCreatedAt() {
      created_at = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'tweet_id_str' field */
    public java.lang.CharSequence getTweetIdStr() {
      return tweet_id_str;
    }
    
    /** Sets the value of the 'tweet_id_str' field */
    public com.learninghadoop2.avrotables.tweets_avro.Builder setTweetIdStr(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.tweet_id_str = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'tweet_id_str' field has been set */
    public boolean hasTweetIdStr() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'tweet_id_str' field */
    public com.learninghadoop2.avrotables.tweets_avro.Builder clearTweetIdStr() {
      tweet_id_str = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'text' field */
    public java.lang.CharSequence getText() {
      return text;
    }
    
    /** Sets the value of the 'text' field */
    public com.learninghadoop2.avrotables.tweets_avro.Builder setText(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.text = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'text' field has been set */
    public boolean hasText() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'text' field */
    public com.learninghadoop2.avrotables.tweets_avro.Builder clearText() {
      text = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'in_reply_to' field */
    public java.lang.CharSequence getInReplyTo() {
      return in_reply_to;
    }
    
    /** Sets the value of the 'in_reply_to' field */
    public com.learninghadoop2.avrotables.tweets_avro.Builder setInReplyTo(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.in_reply_to = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'in_reply_to' field has been set */
    public boolean hasInReplyTo() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'in_reply_to' field */
    public com.learninghadoop2.avrotables.tweets_avro.Builder clearInReplyTo() {
      in_reply_to = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'is_retweeted' field */
    public java.lang.CharSequence getIsRetweeted() {
      return is_retweeted;
    }
    
    /** Sets the value of the 'is_retweeted' field */
    public com.learninghadoop2.avrotables.tweets_avro.Builder setIsRetweeted(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.is_retweeted = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'is_retweeted' field has been set */
    public boolean hasIsRetweeted() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'is_retweeted' field */
    public com.learninghadoop2.avrotables.tweets_avro.Builder clearIsRetweeted() {
      is_retweeted = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'user_id' field */
    public java.lang.CharSequence getUserId() {
      return user_id;
    }
    
    /** Sets the value of the 'user_id' field */
    public com.learninghadoop2.avrotables.tweets_avro.Builder setUserId(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.user_id = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'user_id' field has been set */
    public boolean hasUserId() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'user_id' field */
    public com.learninghadoop2.avrotables.tweets_avro.Builder clearUserId() {
      user_id = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'place_id' field */
    public java.lang.CharSequence getPlaceId() {
      return place_id;
    }
    
    /** Sets the value of the 'place_id' field */
    public com.learninghadoop2.avrotables.tweets_avro.Builder setPlaceId(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.place_id = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'place_id' field has been set */
    public boolean hasPlaceId() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'place_id' field */
    public com.learninghadoop2.avrotables.tweets_avro.Builder clearPlaceId() {
      place_id = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    public tweets_avro build() {
      try {
        tweets_avro record = new tweets_avro();
        record.created_at = fieldSetFlags()[0] ? this.created_at : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.tweet_id_str = fieldSetFlags()[1] ? this.tweet_id_str : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.text = fieldSetFlags()[2] ? this.text : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.in_reply_to = fieldSetFlags()[3] ? this.in_reply_to : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.is_retweeted = fieldSetFlags()[4] ? this.is_retweeted : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.user_id = fieldSetFlags()[5] ? this.user_id : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.place_id = fieldSetFlags()[6] ? this.place_id : (java.lang.CharSequence) defaultValue(fields()[6]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
